import os
import sys
import unicodedata
from PIL import Image, ImageDraw, ImageFont, ImageFilter

# 1. 경로 및 상수 정의 (한글 주석 규정 준수)
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_DIR = os.path.join(BASE_DIR, "ios_en_store_screenshots")

# 폰트 경로 지정
FONT_PATH_B = os.path.join(BASE_DIR, "fonts", "NanumSquareRoundB.ttf")  # 타이틀용 Bold
FONT_PATH_R = os.path.join(BASE_DIR, "fonts", "NanumSquareRoundR.ttf")  # 서브타이틀용 Regular

# 출력 디렉토리 생성
os.makedirs(OUTPUT_DIR, exist_ok=True)

# 2. 통합 배경 테마 색상 정의 (고급스러운 딥 바이올렛 & 다크 미드나잇 그라데이션)
GLOBAL_GRADIENT_START = "#251D3A"  # 딥 바이올렛
GLOBAL_GRADIENT_END = "#090D16"    # 다크 미드나잇

# 3. 스크린샷 이미지와 매칭될 영문 홍보 문구 및 원본 파일 경로 정의
SCREENSHOT_CONFIGS = [
    {
        "filename": "ios_enscreenshot/home.06.png",
        "output_name": "screenshot_1_home.png",
        "title": "Illuminate Your Day with Books",
        "subtitle": "Build healthy reading habits with tailored goals\nand encouraging daily messages.",
        "crop_y": 0
    },
    {
        "filename": "ios_enscreenshot/myLibrary.png",
        "output_name": "screenshot_2_library.png",
        "title": "Your Personal Digital Library",
        "subtitle": "Organize your collection seamlessly with\ncustom bookshelves and status tracking.",
        "crop_y": 0
    },
    {
        "filename": "ios_enscreenshot/bookDetail.png",
        "output_name": "screenshot_3_book_detail.png",
        "title": "Explore Every Book Detail",
        "subtitle": "Access comprehensive metadata, progress,\nand purchase links at a single glance.",
        "crop_y": 0
    },
    {
        "filename": "ios_enscreenshot/stat.png",
        "output_name": "screenshot_4_insights.png",
        "title": "Visualize Your Reading Journey",
        "subtitle": "Track your progress with monthly charts,\ndaily trends, and intuitive reading insights.",
        "crop_y": 0
    },
    {
        "filename": "ios_enscreenshot/AiReport.png",
        "output_name": "screenshot_5_ai_report.png",
        "title": "AI-Powered Reading Persona",
        "subtitle": "Discover your reading persona and get tailored\nbook recommendations generated by AI.",
        "crop_y": 0
    },
    {
        "filename": "ios_enscreenshot/search.png",
        "output_name": "screenshot_6_search.png",
        "title": "Discover Next Favorite Reads",
        "subtitle": "Find books effortlessly and receive AI-curated\nrecommendations tailored just for you.",
        "crop_y": 0
    }
]

# 3.5. 안전 파일 경로 변환 헬퍼 (한글 주석 규정 준수)
def get_safe_file_path(base, rel_path):
    test_abs = os.path.join(base, rel_path)
    if os.path.exists(test_abs):
        return test_abs
        
    parts = rel_path.replace("\\", "/").split("/")
    current = base
    for part in parts:
        if not os.path.exists(current):
            return test_abs
        
        found = False
        norm_nfc = unicodedata.normalize('NFC', part)
        norm_nfd = unicodedata.normalize('NFD', part)
        
        for item in os.listdir(current):
            item_nfc = unicodedata.normalize('NFC', item)
            item_nfd = unicodedata.normalize('NFD', item)
            
            if item_nfc == norm_nfc or item_nfd == norm_nfd:
                current = os.path.join(current, item)
                found = True
                break
        if not found:
            return os.path.join(current, part)
            
    return current

# 4. 2D 선형 그라데이션 배경 생성 함수 (한글 주석 규정 준수)
def create_linear_gradient(width, height, start_hex, end_hex):
    c1 = tuple(int(start_hex.lstrip('#')[i:i+2], 16) for i in (0, 2, 4))
    c2 = tuple(int(end_hex.lstrip('#')[i:i+2], 16) for i in (0, 2, 4))
    
    base = Image.new("RGBA", (width, height))
    draw = ImageDraw.Draw(base)
    
    for y in range(height):
        r = int(c1[0] + (c2[0] - c1[0]) * (y / height))
        g = int(c1[1] + (c2[1] - c1[1]) * (y / height))
        b = int(c1[2] + (c2[2] - c1[2]) * (y / height))
        draw.line([(0, y), (width, y)], fill=(r, g, b, 255))
        
    return base

# 5. 모서리가 둥근 마스크 이미지 생성 함수 (한글 주석 규정 준수)
def create_rounded_mask(size, radius):
    mask = Image.new("L", size, 0)
    draw = ImageDraw.Draw(mask)
    draw.rounded_rectangle([0, 0, size[0], size[1]], radius, fill=255)
    return mask

# 5.1. 이미지 비율 유지 크롭 함수 (한글 주석 규정 준수)
def crop_to_target_aspect_ratio(img, target_w, target_h, crop_y_offset=0):
    orig_w, orig_h = img.size
    target_ratio = target_h / target_w
    orig_ratio = orig_h / orig_w
    
    if orig_ratio >= target_ratio:
        new_h = int(orig_w * target_ratio)
        start_y = crop_y_offset
        if start_y + new_h > orig_h:
            start_y = max(0, orig_h - new_h)
        return img.crop((0, start_y, orig_w, start_y + new_h))
    else:
        new_w = int(orig_h / target_ratio)
        start_x = (orig_w - new_w) // 2
        return img.crop((start_x, 0, start_x + new_w, orig_h))

# 6. 스크린샷 합성 처리 메인 로직 (iPhone 6.9인치 디스플레이 규격: 1320 x 2868)
def generate_screenshots():
    canvas_w, canvas_h = 1320, 2868
    
    # 20% 확대 적용된 디바이스 프레임 크기 및 위치 정의
    device_w, device_h = 960, 2086
    device_x = (canvas_w - device_w) // 2
    device_y = 620
    
    bezel = 22
    screen_w = device_w - (bezel * 2)  # 916px
    screen_h = device_h - (bezel * 2)  # 2042px
    
    # 폰트 로드
    try:
        title_font = ImageFont.truetype(FONT_PATH_B, size=82)
        subtitle_font = ImageFont.truetype(FONT_PATH_R, size=44)
    except IOError:
        try:
            title_font = ImageFont.truetype("/System/Library/Fonts/Helvetica.ttc", size=82, index=0)
            subtitle_font = ImageFont.truetype("/System/Library/Fonts/Helvetica.ttc", size=44, index=0)
        except IOError:
            title_font = ImageFont.load_default()
            subtitle_font = ImageFont.load_default()

    for config in SCREENSHOT_CONFIGS:
        screenshot_path = get_safe_file_path(BASE_DIR, config["filename"])
            
        if not os.path.exists(screenshot_path):
            print(f"Error: Screenshot source file not found: {config['filename']}")
            continue
            
        print(f"Processing: {os.path.basename(screenshot_path)} -> {config['output_name']}")
        
        # 1. 캔버스 배경 그라데이션 생성
        canvas = create_linear_gradient(canvas_w, canvas_h, GLOBAL_GRADIENT_START, GLOBAL_GRADIENT_END)
        
        # 2. 그림자 생성 및 렌더링
        shadow_padding = 72
        shadow_w = device_w + shadow_padding * 2
        shadow_h = device_h + shadow_padding * 2
        shadow_img = Image.new("RGBA", (shadow_w, shadow_h), (0, 0, 0, 0))
        shadow_draw = ImageDraw.Draw(shadow_img)
        shadow_draw.rounded_rectangle(
            [shadow_padding, shadow_padding, shadow_padding + device_w, shadow_padding + device_h],
            radius=174,
            fill=(0, 0, 0, 160)
        )
        shadow_img = shadow_img.filter(ImageFilter.GaussianBlur(36))
        canvas.alpha_composite(shadow_img, (device_x - shadow_padding, device_y - shadow_padding))
        
        # 3. 홍보 문구(타이틀 & 서브타이틀) 렌더링
        draw = ImageDraw.Draw(canvas)
        
        title_text = config["title"]
        title_bbox = draw.textbbox((0, 0), title_text, font=title_font)
        title_w = title_bbox[2] - title_bbox[0]
        title_x = (canvas_w - title_w) // 2
        draw.text((title_x, 180), title_text, fill="#FFFFFF", font=title_font)
        
        subtitle_lines = config["subtitle"].split('\n')
        curr_y = 300
        for line in subtitle_lines:
            sub_bbox = draw.textbbox((0, 0), line, font=subtitle_font)
            sub_w = sub_bbox[2] - sub_bbox[0]
            sub_x = (canvas_w - sub_w) // 2
            draw.text((sub_x, curr_y), line, fill="#E2E8F0", font=subtitle_font)
            curr_y += 62
            
        # 4. 디바이스 프레임 생성
        device_img = Image.new("RGBA", (device_w, device_h), (0, 0, 0, 0))
        dev_draw = ImageDraw.Draw(device_img)
        
        # 외부 어두운 알루미늄 베젤
        dev_draw.rounded_rectangle([0, 0, device_w, device_h], radius=150, fill="#1E1E24")
        # 내부 디스플레이 액정 블랙 테두리
        dev_draw.rounded_rectangle([6, 6, device_w - 6, device_h - 6], radius=144, fill="#050505")
        
        # 5. 스크린샷 이미지 리사이즈 및 크롭
        screen_raw = Image.open(screenshot_path).convert("RGBA")
        screen_cropped = crop_to_target_aspect_ratio(screen_raw, screen_w, screen_h, crop_y_offset=config.get("crop_y", 0))
        screen_resized = screen_cropped.resize((screen_w, screen_h), Image.Resampling.LANCZOS)
        
        screen_mask = create_rounded_mask((screen_w, screen_h), radius=120)
        
        device_img.paste(screen_resized, (bezel, bezel), screen_mask)
        
        # Dynamic Island (다이나믹 아일랜드) 렌더링
        island_w, island_h = 240, 68
        island_x = (device_w - island_w) // 2
        island_y = 28
        dev_draw.rounded_rectangle(
            [island_x, island_y, island_x + island_w, island_y + island_h],
            radius=34,
            fill="#000000"
        )
        
        # 6. 최종 캔버스에 디바이스 합성
        canvas.alpha_composite(device_img, (device_x, device_y))
        
        # 7. 결과 저장
        output_path = os.path.join(OUTPUT_DIR, config["output_name"])
        canvas.convert("RGB").save(output_path, "PNG", quality=95)
        print(f"-> Saved: {output_path}")

    print("\n[SUCCESS] All iOS English App Store Screenshots Generated Successfully!")

if __name__ == "__main__":
    generate_screenshots()
